version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      echo "Build started on `date`"
      echo "Preparing artifact for Elastic Beanstalk"

artifacts:
  files:
    - '**/*'
  discard-paths: no
